### ISSUE TITLE
example（diameter-openims）mvn clean install failure

### ISSUE THREAD

**Issue by JeffKingCN** [Mobicents/sip-servlets#55]
root@ubuntu-vm:/opt/sip-servlets-sip-servlets-release-2.1.547/sip-servlets-examples/diameter-openims# mvn clean install
[INFO] Scanning for projects...
Downloading: http://download.java.net/maven/2//org/mobicents/servlet/sip/examples/sip-servlets-examples-parent/3.0.0-SNAPSHOT/sip-servlets-examples-parent-3.0.0-SNAPSHOT.pom
Downloading: https://oss.sonatype.org/content/groups/public/org/mobicents/servlet/sip/examples/sip-servlets-examples-parent/3.0.0-SNAPSHOT/sip-servlets-examples-parent-3.0.0-SNAPSHOT.pom
Downloading: https://repository.jboss.org/nexus/content/groups/public//org/mobicents/servlet/sip/examples/sip-servlets-examples-parent/3.0.0-SNAPSHOT/sip-servlets-examples-parent-3.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: null:diameter-openims:war:null

Reason: Cannot find parent: org.mobicents.servlet.sip.examples:sip-servlets-examples-parent for project: null:diameter-openims:war:null for project null:diameter-openims:war:null

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Cannot find parent: org.mobicents.servlet.sip.examples:sip-servlets-examples-parent for project: null:diameter-openims:war:null for project null:diameter-openims:war:null
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:378)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.mobicents.servlet.sip.examples:sip-servlets-examples-parent for project: null:diameter-openims:war:null for project null:diameter-openims:war:null
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1370)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:821)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
	at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
	... 11 more
Caused by: org.apache.maven.project.ProjectBuildingException: POM 'org.mobicents.servlet.sip.examples:sip-servlets-examples-parent' not found in repository: Unable to download the artifact from any repository

  org.mobicents.servlet.sip.examples:sip-servlets-examples-parent:pom:3.0.0-SNAPSHOT

from the specified remote repositories:
  mobicents-public-repository-group (https://oss.sonatype.org/content/groups/public),
  jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/),
  maven2-repository.dev.java.net (http://download.java.net/maven/2/),
  central (http://repo1.maven.org/maven2)
 for project org.mobicents.servlet.sip.examples:sip-servlets-examples-parent
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:603)
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1366)
	... 17 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

  org.mobicents.servlet.sip.examples:sip-servlets-examples-parent:pom:3.0.0-SNAPSHOT

from the specified remote repositories:
  mobicents-public-repository-group (https://oss.sonatype.org/content/groups/public),
  jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/),
  maven2-repository.dev.java.net (http://download.java.net/maven/2/),
  central (http://repo1.maven.org/maven2)

	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:212)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:74)
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:556)
	... 18 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
	at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:331)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:200)
	... 20 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32 seconds
[INFO] Finished at: Tue Apr 14 07:31:50 CEST 2015
[INFO] Final Memory: 2M/4M
[INFO] ------------------------------------------------------------------------

**Comment by deruelle** [comment]
Please build the sipservlets project first at the root or update the pom.xml of this project to one of the versions here https://oss.sonatype.org/content/repositories/releases/org/mobicents/servlet/sip/sip-servlets-bootstrap/

**Comment by ssogunle** [comment]
Hi,

 I am a bit of challenge making the openims diameter solution compile on eclipse.

I had the issue stated earlier but I fixed it by building from root folder as jean suggested.

Now, to deploy on Mobicents-JBOSS AS,  I receive the following message. 
-------------------------------------
^[[0m^[[31m14:40:57,898 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC00001: Failed to start service jboss.deployment.unit."diameter-openims-3.0.0-SNAPSHOT.war".POST_MODULE: org.jboss.msc.$
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:127) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.4.GA.jar:1.0.4.GA]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.4.GA.jar:1.0.4.GA]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) [rt.jar:1.6.0_36]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.6.0_36]
        at java.lang.Thread.run(Thread.java:701) [rt.jar:1.6.0_36]
Caused by: java.lang.RuntimeException: JBAS018757: Error getting reflective information for class org.mobicents.servlet.sip.example.DiameterOpenIMSSipServlet with ClassLoader ModuleClassLoader for Module "$
        at org.jboss.as.server.deployment.reflect.DeploymentReflectionIndex.getClassIndex(DeploymentReflectionIndex.java:72) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
        at org.jboss.as.ee.metadata.MethodAnnotationAggregator.runtimeAnnotationInformation(MethodAnnotationAggregator.java:58)
        at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.handleAnnotations(InterceptorAnnotationProcessor.java:107)
        at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.processComponentConfig(InterceptorAnnotationProcessor.java:92)
        at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.deploy(InterceptorAnnotationProcessor.java:77)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:120) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
        ... 5 more
Caused by: java.lang.NoClassDefFoundError: Lorg/mobicents/servlet/sip/example/DiameterShClient;
        at java.lang.Class.getDeclaredFields0(Native Method) [rt.jar:1.6.0_36]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2459) [rt.jar:1.6.0_36]
        at java.lang.Class.getDeclaredFields(Class.java:1808) [rt.jar:1.6.0_36]
        at org.jboss.as.server.deployment.reflect.ClassReflectionIndex.<init>(ClassReflectionIndex.java:57) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
        at org.jboss.as.server.deployment.reflect.DeploymentReflectionIndex.getClassIndex(DeploymentReflectionIndex.java:68) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.mobicents.servlet.sip.example.DiameterShClient from [Module "deployment.diameter-openims-3.0.0-SNAPSHOT.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190) [jboss-modules.jar:1.2.0.CR1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468) [jboss-modules.jar:1.2.0.CR1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456) [jboss-modules.jar:1.2.0.CR1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:423) [jboss-modules.jar:1.2.0.CR1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398) [jboss-modules.jar:1.2.0.CR1]
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120) [jboss-modules.jar:1.2.0.CR1]
        ... 15 more

AND the diameter-openims-3.0.0.SNAPSHOT.war.failed file shows: 

--------------------------------------
^[[0m^[[31m14:40:57,902 ERROR [org.jboss.as.server] (DeploymentScanner-threads - 1) JBAS015870: Deploy of deployment "diameter-openims-3.0.0-SNAPSHOT.war" was rolled back with the following failure message$
{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"diameter-openims-3.0.0-SNAPSHOT.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"diameter-openims-3$
    Caused by: java.lang.RuntimeException: JBAS018757: Error getting reflective information for class org.mobicents.servlet.sip.example.DiameterOpenIMSSipServlet with ClassLoader ModuleClassLoader for Modu$
    Caused by: java.lang.NoClassDefFoundError: Lorg/mobicents/servlet/sip/example/DiameterShClient;
    Caused by: java.lang.ClassNotFoundException: org.mobicents.servlet.sip.example.DiameterShClient from [Module \"deployment.diameter-openims-3.0.0-SNAPSHOT.war:main\" from Service Module Loader]"}}
^[[0m^[[0m14:40:57,906 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015877: Stopped deployment diameter-openims-3.0.0-SNAPSHOT.war (runtime-name: diameter-openims-3.0.0-SNAPSHOT.war)$
^[[0m

-------------------------------------

Please what am I doing wrong? How can I fix this?

**Comment by deruelle** [comment]
Please open a thread on https://groups.google.com/forum/#!forum/mobicents-public.
Please make sure you have deployed the as7 Diameter Mux service from http://sourceforge.net/projects/mobicents/files/Mobicents%20Diameter/mobicents-diameter-1.6.0.FINAL/
