### ISSUE TITLE
NullPointerException when calling SipSession.getCallId() from SipSessionListener.sessionCreated()

### ISSUE THREAD

**Issue by deruelle** [Mobicents/sip-servlets#57]
I implement SipSessionListener.sessionCreated() and call SipSession.getCallId() for logging purposes. I get the following NullPointerException:
09:53:37,769 ERROR [org.mobicents.servlet.sip.core.session.SipSessionImpl] (SIP-TCP-Core-PipelineThreadpool-0) SipSessionListener threw exception: java.lang.NullPointerException 
at org.mobicents.servlet.sip.core.session.SipSessionImpl.getCallId(SipSessionImpl.java:736) 
at org.mobicents.servlet.sip.message.MobicentsSipSessionFacade.getCallId(MobicentsSipSessionFacade.java:108)

**Comment by deruelle** [comment]
https://telestax.atlassian.net/browse/MSS-141
