### ISSUE TITLE
NPE when trying to create client transaction for a Request with WS transport

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/sip-servlets#62]
When a sip endpoint tries to call a sip endpoint that uses WS (jisti clients calls Olympus) there is an NPE when trying to create client transaction for the given INVITE request at:

gov.nist.javax.sip.SipProviderImpl.createClientTransaction(Request, Hop)
      String transport = hop.getTransport();
      ListeningPointImpl listeningPoint = (ListeningPointImpl) this
        .getListeningPoint(transport);

Problem is that gov.nist.javax.sip.SipProviderImpl.listeningPoints ConcurrentHashMap contains only UDP listening point.

This was tested at Mobicents Restcomm 7.3.1.651 on JBoss AS7.

**Comment by deruelle** [comment]
Can you provide full DEBUG logs for such a failing call ?

**Comment by deruelle** [comment]
http://pastebin.com/Mqcun7qJ

**Comment by deruelle** [comment]
http://pastebin.com/Wg7facG4

**Comment by gvagenas** [comment]
@deruelle, Jean find here the logs at debug log level along with the versions of SipServlets, Jain-SIP-RI and Restcomm https://gist.github.com/gvagenas/93f43ee17a654deed736

**Comment by deruelle** [comment]
found the issue : The 2 pieces of code under https://github.com/Mobicents/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/JainSipUtils.java#L682 do not check for WebSockets or WebSockets Secure transport

**Comment by atsakiridis** [comment]
@deruelle, tried with build 652 but still getting the same issue:

: java.lang.IllegalStateException: Error sending request INVITE sip:bob@192.168.2.43:55420;transport=ws SIP/2.0
Call-ID: a77155a96d10f39ab8e8963a2a14007e@192.168.2.32
CSeq: 1 INVITE
From: <sip:alice@192.168.2.32>;tag=44094763_9a51baad_57a5b08a_4eb32605
To: <sip:bob@telestax.com>
Max-Forwards: 70
User-Agent: Mobicents Restcomm 7.3.1.652
Content-Type: application/sdp
Content-Length: 1789

v=0
o=- 916122921487166096 2 IN IP4 192.168.2.43
s=Restcomm B2BUA
t=0 0
a=group:BUNDLE audio video
a=msid-semantic:WMS CgesYGOV6iiMXbJcvGKUorJVhnLefNcg6QuL
m=audio 52505 RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 79.167.45.158
a=rtcp:55859 IN IP4 79.167.45.158
a=candidate:414680299 1 udp 2122260223 192.168.2.43 52505 typ host generation 0
a=candidate:414680299 2 udp 2122260222 192.168.2.43 55859 typ host generation 0
a=candidate:1446279195 1 tcp 1518280447 192.168.2.43 0 typ host tcptype active generation 0
a=candidate:1446279195 2 tcp 1518280446 192.168.2.43 0 typ host tcptype active generation 0
a=candidate:4003986751 1 udp 1686052607 79.167.45.158 52505 typ srflx raddr 192.168.2.43 rport 52505 generation 0
a=candidate:4003986751 2 udp 1686052606 79.167.45.158 55859 typ srflx raddr 192.168.2.43 rport 55859 generation 0
a=ice-ufrag:Yy7MSlEqbY4zP0tu
a=ice-pwd:x6ozx79rYoj0g4ohjnguSccx
a=fingerprint:sha-256 73:6E:CE:E7:56:41:E2:31:41:08:1A:FB:89:94:34:58:C9:B6:D3:2C:EA:FF:01:82:F8:82:41:12:01:4E:9E:5A
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3250086375 cname:ztmDT58XDaepZmWb
a=ssrc:3250086375 msid:CgesYGOV6iiMXbJcvGKUorJVhnLefNcg6QuL 6672c4ed-13c8-41cb-89bc-644300d18f85
a=ssrc:3250086375 mslabel:CgesYGOV6iiMXbJcvGKUorJVhnLefNcg6QuL
a=ssrc:3250086375 label:6672c4ed-13c8-41cb-89bc-644300d18f85

	at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1384)
	at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1016)
	at org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper.redirectToB2BUA(B2BUAHelper.java:149) [restcomm.telephony.api-7.3.1.652.jar:]
	at org.mobicents.servlet.restcomm.telephony.CallManager.invite(CallManager.java:336) [restcomm.telephony-7.3.1.652.jar:]
	at org.mobicents.servlet.restcomm.telephony.CallManager.onReceive(CallManager.java:623) [restcomm.telephony-7.3.1.652.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.NullPointerException
	at gov.nist.javax.sip.SipProviderImpl.createClientTransaction(SipProviderImpl.java:389) [jain-sip-ri-1.2.233.jar:1.2.233]
	at gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:455) [jain-sip-ri-1.2.233.jar:1.2.233]
	at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1220)
	... 14 more

**Comment by atsakiridis** [comment]
@deruelle, tried with build 653. Here are the logs:

http://pastebin.com/aD49YNpG

**Comment by atsakiridis** [comment]
@deruelle, retried with 653 and updated log flags:

http://pastebin.com/AiJrJpGN

**Comment by atsakiridis** [comment]
@deruelle, yet another try this with DEBUG for org.mobicents and commented out org.mobicents.servlet.sip:

http://pastebin.com/MdkFamr8

**Comment by atsakiridis** [comment]
@deruelle, Updated root logger as well:

https://drive.google.com/open?id=0BwfD74mG87iMSGxQSzRIVE5aV0U&authuser=0

**Comment by deruelle** [comment]
Verified
