### ISSUE TITLE
NullPointerException in SipDialog.doDeferredDelete()

### ISSUE THREAD

**Issue by AlerantAppNGIN** [Mobicents/sip-servlets#85]
An NPE occurs in SipDialog.doDeferredDelete():
 
15:22:45,226 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (Mobicents-SIP-Servlets-UDPMessageChannelThread-2) <message
from="127.0.0.1:15080" 
to="127.0.0.1:5080" 
time="1444656165226"
isSender="false" 
transactionId="z9hg4bk5ce86bab_04aaf0e5_a2926c44-6513-4ec3-b985-7698f2625177" 
callId="13162e8b7ff25989ddaf1e9cf9c194c8@127.0.0.1" 
firstLine="SIP/2.0 481 Call leg/Transaction does not exist" 
> 
<![CDATA[SIP/2.0 481 Call leg/Transaction does not exist
CSeq: 1 INFO
Call-ID: 13162e8b7ff25989ddaf1e9cf9c194c8@127.0.0.1
From: <sip:127.0.0.1:5080;c>;tag=85397666_b4b4b11f_04aaf0e5_5ce86bab
To: <sip:127.0.0.1:15080>;tag=26651968_d6498780_1180947b_a9e165f1
Via: SIP/2.0/UDP 127.0.0.1:5080;branch=z9hG4bK5ce86bab_04aaf0e5_a2926c44-6513-4ec3-b985-7698f2625177
Server: Mobicents Sip Servlets 3.0.0-SNAPSHOT
Contact: <sip:127.0.0.1:15080>
Content-Length: 0
 
]]>
</message>
 
15:22:45,391 ERROR [gov.nist.javax.sip.EventScanner] (Mobicents-SIP-Servlets-UDPMessageChannelThread-2) Error: java.lang.NullPointerException
         at gov.nist.javax.sip.stack.SIPDialog.doDeferredDelete(SIPDialog.java:1500) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:312) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.DialogFilter.processResponse(DialogFilter.java:1514) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.stack.SIPClientTransactionImpl.nonInviteClientTransaction(SIPClientTransactionImpl.java:629) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.stack.SIPClientTransactionImpl.processResponse(SIPClientTransactionImpl.java:534) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.stack.SIPClientTransactionImpl.processResponse(SIPClientTransactionImpl.java:1621) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:603) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:512) [jain-sip-ri-1.2.242.jar:1.2.242]
         at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:317) [jain-sip-ri-1.2.242.jar:1.2.242]
         at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60]
 
 
This error occurs when a "waiting for an ACK to receive" timer thread is cancelled and a 481 Response arrives after that. NPE occurs because lastTransaction field is null:
 
            sipStack.getTimer().schedule(
                    this.dialogDeleteTask,
                    SIPTransaction.TIMER_H
                            * lastTransaction.getBaseTimerInterval());
 
lastTransaction is set to null by DialogTimerTask’s cleanUpBeforeCancel() method’s cleanUpOnAck() call which cleans up a huge amout of the variables of dialog instance, but only if gov.nist.javax.sip.AGGRESSIVE_CLEANUP property is set to true in mss-sipstack.properties.
 
However in doDeferredDeleteIfNoAckSent() there is a null check on the lastTransaction field:
 
            int delay = SIPTransactionStack.BASE_TIMER_INTERVAL;
            if(lastTransaction != null) {
                    delay = lastTransaction.getBaseTimerInterval();
            }
 
Doing something similar in doDeferredDelete() migth solve this issue, for example:
 
            int delay = SIPTransaction.TIMER_H * SIPTransactionStack.BASE_TIMER_INTERVAL;
            if(lastTransaction != null) {
                    delay = SIPTransaction.TIMER_H * lastTransaction.getBaseTimerInterval();
            }

**Comment by deruelle** [comment]
Please open issue at https://java.net/projects/jsip or https://github.com/Mobicents/jain-sip
