### ISSUE TITLE
java.lang.IllegalStateException occured in wildfly 8 when ServletTimer created in SipServlet.init()

### ISSUE THREAD

**Issue by AlerantAppNGIN** [Mobicents/sip-servlets#86]
If there is a avax.servlet.sip.TimerService.createTimer() call in SipServlet's init() method, the following exception will be thrown during server startup:

: java.lang.IllegalStateException: No Timer listeners have been configured for this application 
        at org.mobicents.servlet.sip.core.timers.TimerServiceImpl.createTimer(TimerServiceImpl.java:107)
        at hu.alerant.appngin.asc.el.sip.adapters.TimerServiceAdapter.createTimer(TimerServiceAdapter.java:35)
        at hu.alerant.appngin.asc.el.sip.servlets.SipServletResources.createAppTimer(SipServletResources.java:86)
        at hu.alerant.appngin.asc.el.sip.failover.SipAsLoadBalancer.<init>(SipAsLoadBalancer.java:96)
        at hu.alerant.appngin.asc.el.sip.failover.SipAsLoadBalancer.initialize(SipAsLoadBalancer.java:66)
        at hu.alerant.appngin.asc.el.sip.servlets.MainServlet.lambda$init$149(MainServlet.java:52)
        at java.util.Optional.ifPresent(Optional.java:159) [rt.jar:1.8.0_60]
        at hu.alerant.appngin.asc.el.sip.servlets.MainServlet.init(MainServlet.java:51)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:79)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:220)
        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:125)
        at org.mobicents.servlet.sip.undertow.SipContextImpl.start(SipContextImpl.java:242)
        at org.mobicents.as8.deployment.SIPWebContext.start(SIPWebContext.java:298)
        at org.mobicents.as8.deployment.UndertowSipDeploymentService.start(UndertowSipDeploymentService.java:67)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]

The issue occurs only in wildfly 8.

**Comment by AlerantAppNGIN** [comment]
To fix this, we have to load the listeners to the sip context before we start the context.
